backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
# publish_mode: editorial_workflow
media_folder: "assets/imgs/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "milestones"
    label: "Milestones"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Milestone Type"
        name: "type"
        widget: "select"
        options:
          - { label: "Latest", value: "latest" }
          - { label: "Future", value: "future" }
          - { label: "Complete", value: "complete" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Files"
        name: "files"
        widget: "list"
        summary: "{{fields.filename}}"
        fields:
          - { label: File, name: fileupload, widget: file }
          - { label: File Name, name: filename, widget: string }
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - label: "Project Hub"
        name: "hub"
        file: "index.md"
        fields:
          - {
              label: "Title",
              name: "title",
              widget: "hidden",
              default: "about",
            }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "about",
            }
           - { label: "SF Logo Link", name: "sflink", widget: "string", default: "https://superfriendly.com/" }
          - { label: "Client Logo", name: "clientlogo", widget: "image" }
          - { label: "Client Logo URL", name: "clienturl", widget: "string" }
          - label: "Quick Links"
            name: "quicklinks"
            widget: "list"
            summary: "{{fields.linktext}}"
            fields:
              - { label: Link, name: link, widget: string }
              - { label: Link Text, name: linktext, widget: string }
